# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: npm install
      - name: Build CSS
        run: |
          npm run build:scss
          npm run build
      - name: Commit files
        run: |
          git config --global user.name "Konata09"
          git config --global user.email "lz9709@gmail.com"
          git add -f dist
          git commit -m "Auto built from ${{ github.sha }}" || echo "Nothing to update"
      - name: Push changes
        run: git push
